# You can apparently get this from https://discovery.meethue.com (apparently your bridge may need to be "discoverable"?)
# If your internet dies this may change so you will have to redo this step.
HUE_URL: http://192.168.86.34

# Your light group number, 0 means all of them.
HUE_ID: 0

# Create a Twitch application here: https://dev.twitch.tv/console/apps/create
# (Twitch will complain if you don't have 2-Factor Authentication enabled though)
# Set the OAuth Redirect URL to http://localhost:17563
CLIENT_ID: 12345
CLIENT_SECRET: abcde

# Twitch username
USERNAME: bigpeep3estreamer
# Channel Point Reward Name (make this match the actual reward)
REWARD_NAME: Change light color

# Set to True to force the light on (if it was otherwise turned off) when a color change request comes through. Set to False to make it not do that.
FORCE_ON: true

# A value from 0 to 100. The minimum brightness value allowed for the light to be. 
MINIMUM_BRIGHTNESS: 0

# A value from 0 to 100. The maximum brightness value allowed for the light to be. 
MAXIMUM_BRIGHTNESS: 100

# Debug mode. Set to true for testing purposes.
DEBUG: false

# Whisper test mode. Set to true to test for whispers instead.
# IMPORTANT: Delete twitch_secrets.json whenever this is changed.
WHISPER_MODE: false